# Local Development Profile (H2 Database)

## Database Configuration
#spring.datasource.url=jdbc:h2:mem:chatdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#
## H2 Console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# Datasource (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/realtime_chat_server?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Kafka Consumer
spring.kafka.consumer.group-id=chatting
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Kafka Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.application.name=backend

jwt.secret=0e8c2fc4ba72875f09ad3068a654bef466bf3d2d39605a7a3e29acb5bad91cbd
